# Use the -g tag to compile for use with gdb
Interpreter_Program:
	g++ -Wall chunk.cpp compiler.cpp debug.cpp main.cpp memory.cpp scanner.cpp value.cpp vm.cpp object.cpp table.cpp -O2 -o Interpreter_Program

clean:
	rm Interpreter_Program